import { makeStyles } from "@material-ui/core/styles";

export default makeStyles(() => ({
  card1: {
    backgroundColor: "#d5d5d5",
    // backgroundColor: "black",
    margin: "10px",
    width: "110px",
    height: "150px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "25px",
  },
  blackCard1: {
    // backgroundColor: "#d5d5d5",
    backgroundColor: "black",
    margin: "10px",
    width: "109px",
    height: "149px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "25px",
  },
  avatar: {
    width: "70px",
    height: "70px",
    backgroundColor: "white",
  },
  avatarBlack: {
    // paddingTop: "10px",
    marginTop: "30px",
    // marginLeft: "20px",
    width: "70px",
    height: "70px",
    backgroundColor: "white",
    color: "black",
    textAlign: "center",
    alignSelf: "center",
  },
  avatarColor1: {
    width: "35px",
    height: "35px",
    backgroundColor: "#00c853",
    color: "#00c853",
    margin: "8px",
    marginTop: "0px",
  },
  avatarColor2: {
    width: "35px",
    height: "35px",
    backgroundColor: "red",
    color: "red",
    margin: "8px",
    marginTop: "0px",
  },
  checkIcon: {
    // position: "relative",
    width: "35px",
    height: "35px",
    backgroundColor: "red",
    color: "white",
    margin: "8px",
    marginTop: "0px",
    marginBottom: "20px",
    zIndex: "100",
    // visibility: "hidden",
  },
  clearIcon: {
    // position: "absolute",
    width: "35px",
    height: "35px",
    backgroundColor: "green",
    color: "white",
    margin: "8px",
    marginTop: "0px",
    // visibility: "hidden",
  },
  avatarBlack: {
    width: "70px",
    height: "70px",
    backgroundColor: "white",
    marginLeft: "15px",
    marginTop: "-5px",
  },
  name: {
    fontSize: "16px",
    marginBottom: "-20px",
    color: "white",
    textAlign: "center",
  },
}));
